# 生产环境配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: developer
    password: Qx310320.n
    url: jdbc:mysql://127.0.0.1:3306/swms?useUnicode=true&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 8
          min-idle: 0
      password: Qx310320.n

mybatis-flex:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    print-banner: false
  type-aliases-package: edu.guet.studentworkmanagementsystem.entity

logging:
  level:
    edu.guet.studentworkmanagementsystem.mapper: trace
jwt:
  expire-time: 7
  key: edu.guet